pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label=merge me
      - check-success=nix
      - check-success=stack
      - check-success=Haskell GHC 8.10
    actions:
      merge:
        method: rebase
        strict: smart+fasttrack
  - actions:
      delete_head_branch: {}
    name: Delete head branch after merge
    conditions:
      - merged
