name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - uses: cachix/install-nix-action@v13
    - run: nix-build --attr podenv
    - run: ./result/bin/podenv --list
